env:
  RUBY_VERSION: '2.6.6'

name: Tests
on: [push, pull_request]
jobs:
  rspec-test:
    name: Rspec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Run tests
        run: bundler exec rspec
      - name: Upload coverage results
        uses: codecov/codecov-action@v1
        with:
          name: coverage-report
          file: ./coverage.xml
          directory: ./coverage/reports/
          path_to_write_report: ./coverage/codecov_report.gz
